Feature/filter on played
GAsplund/GAMES pull request #108
Opened 2023-05-10 07:32 UTC by x183

Added ability to filter games on whether they were played by the user or not, fixes #6

2023-05-10 09:02 UTC, Supergamer1337 commented
Why does it have a lot of rating stuff?

2023-05-10 09:10 UTC, Supergamer1337 requested changes

2023-05-10 09:10 UTC, Supergamer1337 commented on backend/src/routers/gameRouter.ts
> +		}
It's not possible to do this with a DB call?

2023-05-10 09:10 UTC, Supergamer1337 commented on frontend/src/components/GamesList/GamesList.tsx
> +		console.log(searchFilter);
Why is this still here?
```suggestion
```

2023-05-10 09:10 UTC, Supergamer1337 commented on frontend/src/components/GamesList/GamesList.tsx
> +		console.log(searchFilter);
Why is this still here?
```suggestion
```

2023-05-12 11:55 UTC, x183 commented
wrong pr, sorry 😓

2023-05-15 08:19 UTC, x183 commented
I'll continue with this after the current sprint is finished

2023-05-15 08:19 UTC, closed without merging