Feature/right req
GAsplund/GAMES pull request #119
Opened 2023-05-15 12:39 UTC by EmilMadsstuen

Users can now only see burrow requests for games that they own or for games administrated by organizations where they are admins. Fixes #95

2023-05-16 11:00 UTC, Supergamer1337 requested changes

2023-05-16 11:01 UTC, x183 commented on frontend/src/components/BorrowRequestsList/BorrowRequestsList.tsx
>  	return (
No! :triumph:

2023-05-16 11:05 UTC, Supergamer1337 commented on frontend/src/components/BorrowRequestsList/BorrowRequestsList.tsx
>  	const { data, error, loading } = useApiGet<BorrowRequest[]>(apiPath);
Keep line or I angry
```suggestion
	const [apiPath, setApiPath] = useState("/borrow/request/list")
	const { data, error, loading } = useApiGet<BorrowRequest[]>(apiPath);
	
```

2023-05-16 15:36 UTC, EmilMadsstuen commented on backend/src/routers/borrowRequestRouter.ts
> +	}
Should I catch the error maybe? I think it should be impossible to see the requests if you are not logged in.

2023-05-16 17:07 UTC, EmilMadsstuen commented on backend/src/services/borrowRequestService.ts
> +	const organizationMemberships = await prisma.organizationMember.findMany({ //Get all the orgz where login is admin
Should be fixed now

2023-05-16 17:17 UTC, EmilMadsstuen commented on backend/src/routers/borrowRequestRouter.ts
> +	}
@Supergamer1337 I can't find a good solution. Do you have any tips?

2023-05-16 17:23 UTC, EmilMadsstuen reviewed
Did it a bit quickly. Does not work...

2023-05-16 18:21 UTC, Supergamer1337 commented on backend/src/routers/borrowRequestRouter.ts
> +	}
There should be an `isAuthenricated` middleware that you can use. Just search for `isAuthenticated` in the code base for an example of how to use (I would suggest it, but I'm on my phone)

2023-05-17 06:27 UTC, x183 commented on backend/src/routers/borrowRequestRouter.ts
> +	'/list',
```suggestion
	'/list',
 isAuthenticated,
```

2023-05-17 06:28 UTC, x183 commented
Merge conflict! 😭

2023-05-17 07:29 UTC, Oscariremma requested changes
We need to run prettier before merging as well

2023-05-17 07:29 UTC, Oscariremma commented on backend/src/routers/borrowRequestRouter.ts
> +		const requests = await getActiveBorrowRequests();
We need to pass the user
```suggestion
		const requests = await getActiveBorrowRequests(user);
```

2023-05-17 07:29 UTC, Oscariremma commented on backend/src/routers/borrowRequestRouter.ts
> +		let requestResponse = `Request ${body.approved ? 'accepted' : 'rejected'
```suggestion
		const requestResponse = `Request ${body.approved ? 'accepted' : 'rejected'
```

2023-05-18 09:27 UTC, Oscariremma approved these changes
LGTM

2023-05-18 11:24 UTC, Supergamer1337 approved these changes
LGTM

2023-05-18 11:25 UTC, merged