Added game borrowing
GAsplund/GAMES pull request #55
Opened 2023-04-21 14:39 UTC by x183

Added indicators on game borrowing status, fixes #18

2023-04-21 15:32 UTC, x183 commented
Please squash this when merging

2023-04-21 15:40 UTC, GAsplund approved these changes
LGTM!

2023-04-21 16:20 UTC, Oscariremma requested changes

2023-04-21 16:20 UTC, Oscariremma commented on backend/src/routers/borrowRouter.ts
> + * @api {post} /api/v1/games/borrow Borrow a game
Correct endpoint in apidoc
```suggestion
 * @api {post} /api/v1/borrow Borrow a game
```

2023-04-21 16:20 UTC, Oscariremma commented on backend/src/routers/borrowRouter.ts
> + * @api {post} /api/v1/games/return Returns a borrowed game
Correct endpoint in apidoc
```suggestion
 * @api {post} /api/v1/borrow/return Returns a borrowed game
```

2023-04-21 16:23 UTC, Oscariremma approved these changes
Looks good!

2023-04-21 16:24 UTC, merged

2023-04-22 11:33 UTC, Supergamer1337 commented
I know this got merged, but why can I borrow games that don't exist?

2023-04-22 11:34 UTC, Supergamer1337 commented
I can also borrow something that is already borrowed?

2023-04-22 11:44 UTC, x183 commented
> I can also borrow something that is already borrowed?

Yes, and return something twice 😃