Fix/filter playtime range
GAsplund/GAMES pull request #81
Opened 2023-05-02 07:53 UTC by x183

Filters games on a range of playtimes instead of just a single number, fixes #72

2023-05-02 12:07 UTC, x183 commented
> Seems like branch was not based on main? And I will see with our stakeholder what the preferred way to filter amount of players is

Oopsie woopsie, something seems to have went wong, is fix now :+1:

2023-05-03 08:03 UTC, Supergamer1337 requested changes

2023-05-03 08:18 UTC, x183 commented on backend/src/routers/gameRouter.ts
> +		if (body.playtimeMax && filter.playtimeMinutes)
I totally agree with you, sadly Typescript does not :pensive:

2023-05-03 08:34 UTC, Supergamer1337 commented on backend/src/routers/gameRouter.ts
> +		if (body.playtimeMax && filter.playtimeMinutes)
Worked fine for me when I removed it

2023-05-03 12:21 UTC, Supergamer1337 approved these changes
LGTM

2023-05-04 12:26 UTC, Krysset commented
> Seems like branch was not based on main? And I will see with our stakeholder what the preferred way to filter amount of players is

Mistook PR for another.... Whoopsie

2023-05-04 12:26 UTC, Krysset approved these changes
Looks good!

2023-05-04 13:27 UTC, merged